name: Docs
on:
  push:
    branches:
      - main
    paths:
      - 'documentation/**'
      - '.github/workflows/documentation.yml'
env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
jobs:
  publish_documentation:
    name: Publish documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - name: Build documentation
        run: pnpm docs:build

      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=documentation/public --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
